# Generated by Django 4.0.5 on 2022-10-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_remove_employee_email'),
        ('accounts', '0004_alter_memberinvite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinvite',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='hospital.department'),
        ),
    ]
