# Generated by Django 4.0.5 on 2022-09-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveSmallIntegerField()),
                ('invoices', models.PositiveSmallIntegerField()),
                ('months', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('payment_intent_id', models.CharField(max_length=255)),
                ('hospital_name', models.CharField(max_length=255, unique=True)),
                ('currency', models.PositiveSmallIntegerField(choices=[(1, 'USD')], default=1)),
                ('payment_method_types', models.PositiveSmallIntegerField(choices=[(1, 'card')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
