# Generated by Django 4.0.5 on 2022-08-15 19:49

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_department_hospital_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default=accounts.utils.get_formatted_uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
