# Generated by Django 4.0.5 on 2022-10-04 16:40

from django.db import migrations
import hospital.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=hospital.fields.CaseInsensitiveCharField(max_length=255),
        ),
    ]
