# Generated by Django 4.0.5 on 2022-10-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='attribution',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Finance'), (2, 'Patients'), (3, 'Editor')]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
