# Generated by Django 4.0.5 on 2022-10-23 09:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0010_remove_employee_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('user', 'department')},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
