# Generated by Django 4.0.5 on 2022-10-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_alter_employee_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Pending')], default=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='attribution',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Finance'), (2, 'Patients'), (3, 'Editor')]),
        ),
    ]
